import pygame as pg
import os
pg.init()

DISPLAY_WIDTH = 800
DISPLAY_HEIGHT = 600
DISPLAY_MARGIN = 10

FONT_SIZE = 18
FONT = pg.font.Font(os.path.join('assets', 'font', 'CascadiaCode.ttf'), FONT_SIZE)

GENERATION_SIZE = 60

NNET_INPUTS = 2
NNET_HIDDEN = 5 
NNET_OUTPUTS = 1

JUMP_CHANCE = 0.5


MUTATION_WEIGHT_MODIFY_CHANCE = 0.2
MUTATION_ARRAY_MIX_PERC = 0.5
MUTATION_CUT_OFF = 0.4
MUTATION_BAD_TO_KEEP = 0.2
MUTATION_MODIFY_CHANCE_LIMIT = 0.4

SPRINTER = 1
HEAVY = 2